BEGIN TRANSACTION;

CREATE TABLE gauges(
    id VARCHAR(200) UNIQUE NOT NULL PRIMARY KEY,
    g_value DOUBLE PRECISION NOT NULL
);

CREATE TABLE counters(
    id VARCHAR(200) UNIQUE NOT NULL PRIMARY KEY,
    delta INT NOT NULL
);

COMMIT;