codecov:
  bot: "codecov"
  notify:
    wait_for_ci: false
comment:
  layout: "diff flags files footer "
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
