services:
  postgres:
    container_name: postgres
    image: postgres:17.2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gopher -d gopher_corp" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "P@ssw0rd"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - metricsmonitor
    restart: always

  server:
    container_name: server
    build:
      context: .
      dockerfile: build/Dockerfile.server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      ADDRESS: "0.0.0.0:8080"
      DATABASE_DSN: "postgresql://gopher:gopher@postgres:5432/gopher_corp"
    networks:
      - metricsmonitor
    restart: always

volumes:
  postgres:


networks:
  metricsmonitor:
    driver: bridge
