syntax = "proto3";
package proto;

import "google/protobuf/empty.proto";

option go_package = "github.com/zhenyanesterkova/metricsmonitor/internal/app/proto";

message Metric {
    string id = 1;
    string type = 2;
    double value = 3;
    int64 delta = 4;
}

message MetricRequest{
    Metric metric = 1;
}

message MetricsRequest{
    repeated Metric metrics = 1;
}

message MetricResponse{
    Metric metric = 1;
}

message MetricsHTMLResponse{
    string metricsHTML = 1;
}

service Monitor {
    rpc AddMetric(MetricRequest) returns (MetricResponse);
    rpc AddMetrics(MetricsRequest) returns(google.protobuf.Empty);
    rpc GetMetrics(google.protobuf.Empty) returns (MetricsHTMLResponse);
    rpc GetMetric(MetricRequest) returns(MetricResponse);
    rpc Ping(google.protobuf.Empty) returns(google.protobuf.Empty);
}