syntax = "proto3";
package proto;

option go_package = "github.com/zhenyanesterkova/metricsmonitor/internal/app/proto";

message Metric {
    string id = 1;
    string type = 2;
    double value = 3;
    int64 delta = 4;
}

message AddMetricsRequest{
    repeated Metric metrics = 1;
}

message AddMetricsResponse{
}

message AddMetricRequest{
    Metric metric = 1;
}

message AddMetricResponse{
    Metric metric = 1;
}

message GetMetricRequest{
    Metric metric = 1;
}

message GetMetricResponse{
    Metric metric = 1;
}

message GetMetricsRequest{}

message HTMLMetrics{
    string metrics = 1;
}

service Monitor {
    rpc AddMetric(AddMetricRequest) returns (AddMetricResponse);
    rpc AddMetrics(AddMetricsRequest) returns(AddMetricsResponse);
    rpc GetMetrics(GetMetricsRequest) returns (HTMLMetrics);
    rpc GetMetric(GetMetricRequest) returns(GetMetricResponse);
}